### ISSUE TITLE
Imgur InvalidResponse

### ISSUE THREAD

**Issue by wraithy** [Radiicall/jellyfin-rpc#99]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What went wrong?

I was using Jellyfin-RPC fine and then all of a sudden the images stopped working so I assume this has something to do with Imgur and not Jellyfin-RPC but I thought I would open an issue just in case since they may be changing their API.

![image](https://github.com/Radiicall/jellyfin-rpc/assets/83000298/cc282b68-da06-47dc-8d62-a0f5077a2005)

### Jellyfin-RPC version

0.15.5

### What OS are you using?

Windows

### What version is the Jellyfin server on?

10.8.13

**Comment by Radiicall** [comment]
Is this happening with a certain item in your library or just anything? This might be a problem with your network connection or imgur might be ratelimiting jellyfin-rpc (I'm not sure how many uploads and such they allow in a short time span).

If you've used jellyfin-rpc for a while with imgur images then imgur might've deleted the images, Jellyfin-RPC stores the image URLs in a file called urls.json with the main.json file, if you've watched something before and uploaded the image to imgur then it will try to use the one that's already uploaded instead of reuploading. I'm not sure if imgur deletes the images after some time or not though.

**Comment by wraithy** [comment]
It seems to be working now so I assume I was either being rate-limited or my VPN was causing issues since I have all of my traffic going through it unless I explicitly set it not to go through the VPN. I haven't set it to bypass and it seems to be working so I have no idea what the cause was but all of the URLs in the urls.json file are still there and they all work.
